name: club
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^11.1.4
  # Flutter packages
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  # Firebase
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true